### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by ericandrewlewis** [LeaVerou/chainvas#14]
Hi Lea,

this is a nice library :)

I notice the download link is broken since [Chrome now disallows](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM%5B1-25%5D) navigation of the top-frame to data URLS.

Perhaps we could provide a link to a relevant CDN, or the Github source?

**Comment by LeaVerou** [comment]
Hey, thanks for spotting that!
We should use Blob URLs, those still work!

Sadly I don't have the time to do it right now :( Do you?

**Comment by ericandrewlewis** [comment]
Sure thing! I opened up a PR.
